SELECT data_set, 
    date_of_game, 
    player_full_name, 
    "position", 
    own_team, 
    opp_team, 
    renue AS venue, 
    "min", 
    fgm, 
    fga,
    fgm - "3pm" AS "2pm",
    fga - "3pa" AS "2pa", 
    "3pm", 
    "3pa", 
    ftm, 
    fta, 
    oreb, 
    dreb, 
    totreb, 
    ast, 
    pf, 
    stl, 
    tos, 
    blk, 
    pts
FROM {{ ref( 'all_stats' ) }}
WHERE data_set LIKE '%egular%'