SELECT [DATA_SET]
      ,[DATE]
      ,[PLAYER_FULL_NAME]
      ,[POSITION]
      ,[OWN_TEAM]
      ,[OPP_TEAM]
      ,[VENUE_R_H]
      ,[MIN]
      ,[FG]
      ,[FGA]
      ,[_2P] = [FG] - [_3P]
      ,[_2PA] = [FGA] - [_3PA]
      ,[_3P]
      ,[_3PA]
      ,[FT]
      ,[FTA]
      ,[OR]
      ,[DR]
      ,[TOT]
      ,[A]
      ,[PF]
      ,[ST]
      ,[TO]
      ,[BL]
      ,[PTS]
  FROM {{ ref( 'all_stats' ) }}
 WHERE [DATA_SET] LIKE '%egular%'