SELECT dataset, 
    "DATE" as date_of_game, 
    "player_fullname" as player_full_name, 
    "POSITION" as pos, 
    own_team, 
    opponent_team as opp_team, 
    venue, 
    "min", 
    fg as fgm, 
    fga,
    fg - "3P" AS "2pm",
    fga - "3PA" AS "2pa", 
    "3P" as "3pm", 
    "3PA" as "3pa", 
    ft as ftm, 
    fta, 
    "OR" as oreb, 
    dr as dreb, 
    tot as totreb, 
    a as ast, 
    pf, 
    st as stl, 
    "TO" as tos, 
    bl as blk, 
    pts
FROM {{ ref( 'all_stats' ) }}
WHERE dataset LIKE '%egular%'