SELECT dataset, 
       game_id, 
       "DATE", 
       player_id, 
       player_fullname, 
       "POSITION", 
       own_team, 
       opponent_team, 
       venue, 
       starter, 
       min, 
       fg, 
       fga, 
       "3P", 
       "3PA", 
       ft, 
       fta, 
       "OR", 
       dr, 
       tot, 
       a, 
       pf, 
       st, 
       "TO", 
       bl, 
       pts, 
       "USAGE_RATE_%", 
       days_rest
FROM {{ source( 'all_data', '2020_2021_stats' ) }}
UNION ALL
SELECT "DATA SET",
       NULL as game_id,
       "DATE",
       NULL as player_id, 
       "PLAYER FULL NAME", 
       "POSITION", 
       "OWN TEAM", 
       "OPP TEAM", 
       "VENUE (R/H)",
       NULL AS starter, 
       min, 
       fg, 
       fga, 
       "3P", 
       "3PA", 
       ft, 
       fta, 
       "OR", 
       dr, 
       tot, 
       a, 
       pf, 
       st, 
       "TO", 
       bl, 
       pts,
       NULL AS "USAGE_RATE_%",
       NULL AS days_rest
FROM {{ source( 'all_data', '2013_2014_stats' ) }}
UNION ALL
SELECT "DATA SET",
       NULL as game_id,
       "DATE",
       NULL as player_id, 
       "PLAYER FULL NAME", 
       "POSITION", 
       "OWN TEAM", 
       "OPP TEAM", 
       "VENUE (R/H)",
       NULL AS starter, 
       min, 
       fg, 
       fga, 
       "3P", 
       "3PA", 
       ft, 
       fta, 
       "OR", 
       dr, 
       tot, 
       a, 
       pf, 
       st, 
       "TO", 
       bl, 
       pts,
       NULL AS "USAGE_RATE_%",
       NULL AS days_rest
FROM {{ source( 'all_data', '2014_2015_stats' ) }}
UNION ALL
SELECT "DATA SET",
       NULL as game_id,
       "DATE",
       NULL as player_id, 
       "PLAYER FULL NAME", 
       "POSITION", 
       "OWN TEAM", 
       "OPP TEAM", 
       "VENUE (R/H)",
       NULL AS starter, 
       min, 
       fg, 
       fga, 
       "3P", 
       "3PA", 
       ft, 
       fta, 
       "OR", 
       dr, 
       tot, 
       a, 
       pf, 
       st, 
       "TO", 
       bl, 
       pts,
       NULL AS "USAGE_RATE_%",
       NULL AS days_rest
FROM {{ source( 'all_data', '2015_2016_stats' ) }}
UNION ALL
SELECT "DATA SET",
       NULL as game_id,
       "DATE",
       NULL as player_id, 
       "PLAYER FULL NAME", 
       "POSITION", 
       "OWN TEAM", 
       "OPP TEAM", 
       "VENUE (R/H)",
       NULL AS starter, 
       min, 
       fg, 
       fga, 
       "3P", 
       "3PA", 
       ft, 
       fta, 
       "OR", 
       dr, 
       tot, 
       a, 
       pf, 
       st, 
       "TO", 
       bl, 
       pts,
       NULL AS "USAGE_RATE_%",
       NULL AS days_rest
FROM {{ source( 'all_data', '2016_2017_stats' ) }}
UNION ALL
SELECT "DATA SET",
       NULL as game_id,
       "DATE",
       NULL as player_id, 
       "PLAYER FULL NAME", 
       "POSITION", 
       "OWN TEAM", 
       "OPP TEAM", 
       "VENUE (R/H)",
       NULL AS starter, 
       min, 
       fg, 
       fga, 
       "3P", 
       "3PA", 
       ft, 
       fta, 
       "OR", 
       dr, 
       tot, 
       a, 
       pf, 
       st, 
       "TO", 
       bl, 
       pts,
       NULL AS "USAGE_RATE_%",
       NULL AS days_rest
FROM {{ source( 'all_data', '2017_2018_stats' ) }}
UNION ALL
SELECT dataset, 
       game_id, 
       "DATE", 
       player_id, 
       player_fullname, 
       "POSITION", 
       own_team, 
       opponent_team, 
       venue, 
       starter, 
       min, 
       fg, 
       fga, 
       "3P", 
       "3PA", 
       ft, 
       fta, 
       "OR", 
       dr, 
       tot, 
       a, 
       pf, 
       st, 
       "TO", 
       bl, 
       pts, 
       "USAGE_RATE_%", 
       days_rest
FROM {{ source( 'all_data', '2018_2019_stats' ) }}
UNION ALL
SELECT dataset, 
       game_id, 
       "DATE", 
       player_id, 
       player_fullname, 
       "POSITION", 
       own_team, 
       opponent_team, 
       venue, 
       starter, 
       min, 
       fg, 
       fga, 
       "3P", 
       "3PA", 
       ft, 
       fta, 
       "OR", 
       dr, 
       tot, 
       a, 
       pf, 
       st, 
       "TO", 
       bl, 
       pts, 
       "USAGE_RATE_%", 
       days_rest
FROM {{ source( 'all_data', '2019_2020_stats' ) }}
