SELECT [DATA_SET]
       ,[PLAYER_FULL_NAME]
       ,[Percentile_MPG]= PERCENT_RANK() OVER (ORDER BY [MPG])
       ,[Percentile_2P%]= PERCENT_RANK() OVER (ORDER BY [2P%])
       ,[Percentile_3P%]= PERCENT_RANK() OVER (ORDER BY [3P%])
       ,[Percentile_FT%]= PERCENT_RANK() OVER (ORDER BY [FT%])
       ,[Percentile_FG%]= PERCENT_RANK() OVER (ORDER BY [FG%])
       ,[Percentile_FGM/36] = PERCENT_RANK() OVER (ORDER BY [FGM/36])
       ,[Percentile_FGA/36] = PERCENT_RANK() OVER (ORDER BY [FGA/36])
       ,[Percentile_2PM/36] = PERCENT_RANK() OVER (ORDER BY [2PM/36])
       ,[Percentile_2PA/36] = PERCENT_RANK() OVER (ORDER BY [2PA/36])
       ,[Percentile_3PM/36] = PERCENT_RANK() OVER (ORDER BY [3PM/36])
       ,[Percentile_3PA/36] = PERCENT_RANK() OVER (ORDER BY [3PA/36])
       ,[Percentile_FTM/36] = PERCENT_RANK() OVER (ORDER BY [FTM/36])
       ,[Percentile_FTA/36] = PERCENT_RANK() OVER (ORDER BY [FTA/36])
       ,[Percentile_OR/36] = PERCENT_RANK() OVER (ORDER BY [OR/36])
       ,[Percentile_DR/36] = PERCENT_RANK() OVER (ORDER BY [DR/36])
       ,[Percentile_REB/36] = PERCENT_RANK() OVER (ORDER BY [REB/36])
       ,[Percentile_AST/36] = PERCENT_RANK() OVER (ORDER BY [AST/36])
       ,[Percentile_PF/36] = PERCENT_RANK() OVER (ORDER BY [PF/36])
       ,[Percentile_STL/36] = PERCENT_RANK() OVER (ORDER BY [STL/36])
       ,[Percentile_TO/36] = PERCENT_RANK() OVER (ORDER BY [TO/36] DESC)
       ,[Percentile_BLK/36] = PERCENT_RANK() OVER (ORDER BY [BLK/36])
       ,[Percentile_PTS/36] = PERCENT_RANK() OVER (ORDER BY [PTS/36])
  FROM {{ ref( 'regular_season_summary_stats' ) }}