version: 2

sources:
  - name: all_data # this is the source_name
    database: hyperdunk
    schema: import
    tables:
      - name: elo
      - name: historical_stats

  - name: current_season # this is the source_name
    database: hyperdunk
    schema: import
    tables: 
      - name: rosters
      - name: stats
      - name: transactions
