version: 2

sources:
  - name: all_data # this is the source_name
    database: hyperdunk
    schema: import
    tables:
      - name: elo
      - name: historical_stats

  - name: current_season # this is the source_name
    database: hyperdunk
    schema: import
    tables: 
      - name: rosters
        description: export of all players from fantrax. this table is versioned - i.e. every import adds more records to the table
        columns: 
          - name: id
            description: unique id of the player from fantrax
            tests:
              - unique
              - not_null
          - name: player
            description: player first and last name
          - name: team
            description: NBA team abbreviation - players without a team have the value (N/A)
          - name: position
            description: concatenated list of eligbile positions in fantrax
          - name: rkov
            description: overall rank of the player in fantrax
          - name: status
            description: fantasy team that is associated to a player. Free Agents have the value 'FA'
          - name: opponent
            description: opponent name on the day that the data was extracted from fantrax
          - name: score
            description: fantrax assessment of players score relative to others
          - name: _rostered
            description: percentage of leagues where this player is on a roster
          - name: _
            description: change in '_rostered' value of the player since an arbitrary time as defined in fantrax
          - name: gp
            description: games played this season
          - name: min
            description: average number of minutes per game
          - name: fga
            description: number of field goal attempts per game
          - name: fg
            description: field goal percentage (fgm/fga) for the season
          - name: 3ptm
            description: 3 pointers made per game
      - name: stats
      - name: transactions
